package app.lhx.mibandmcp.ui.theme

import androidx.compose.ui.graphics.Color

val TealPrimary = Color(0xFF006A63)
val TealOnPrimary = Color(0xFFFFFFFF)
val TealPrimaryContainer = Color(0xFF9CF2E8)
val TealOnPrimaryContainer = Color(0xFF00201D)
val IndigoSecondary = Color(0xFF4F6078)
val IndigoOnSecondary = Color(0xFFFFFFFF)
val IndigoSecondaryContainer = Color(0xFFD6E4FF)
val IndigoOnSecondaryContainer = Color(0xFF0B1D31)
val AmberTertiary = Color(0xFF765A00)
val AmberOnTertiary = Color(0xFFFFFFFF)
val AmberTertiaryContainer = Color(0xFFFFE17B)
val AmberOnTertiaryContainer = Color(0xFF241A00)
val NeutralBackground = Color(0xFFF7F9F7)
val NeutralSurface = Color(0xFFFBFDFB)
val NeutralSurfaceContainer = Color(0xFFEEF3F1)
val NeutralSurfaceContainerHigh = Color(0xFFE7ECEA)
val NeutralOnSurface = Color(0xFF181D1C)
val NeutralOnSurfaceVariant = Color(0xFF3F4947)
val NeutralOutline = Color(0xFF6F7976)
val NeutralOutlineVariant = Color(0xFFBEC9C6)
val ErrorMuted = Color(0xFFBA1A1A)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)

val DarkPrimary = Color(0xFF7FD2C8)
val DarkOnPrimary = Color(0xFF003733)
val DarkPrimaryContainer = Color(0xFF00504A)
val DarkOnPrimaryContainer = Color(0xFF9CEFE5)
val DarkSecondary = Color(0xFFB8C8E0)
val DarkSecondaryContainer = Color(0xFF37485F)
val DarkTertiary = Color(0xFFE8C349)
val DarkTertiaryContainer = Color(0xFF594400)
val DarkBackground = Color(0xFF0F1513)
val DarkSurface = Color(0xFF111916)
val DarkSurfaceContainer = Color(0xFF19221F)
val DarkSurfaceContainerHigh = Color(0xFF232C29)
val DarkOnSurface = Color(0xFFE0E4E2)
val DarkOnSurfaceVariant = Color(0xFFB8C5C0)
